# fly.toml app configuration file generated for grocery-app on 2023-06-11T13:51:49-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grocery-app"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
